parzer
======

```{r echo=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE
)
```

`parzer` parses coordinates

Code originally from: https://www.codeproject.com/Articles/15659/Longitude-Latitude-String-Parser-and-Formatter

Code retrieved from: https://github.com/batela/Gaypu-Src/blob/master/ll2utm/src/llstr.cpp


## Installation

```{r eval=FALSE}
devtools::install_github("ropenscilabs/parzer")
```

```{r}
library("parzer")
```

## parse

latitudes

```{r}
parse_lat("45N54.2356")
parse_lat("-45.98739874")
parse_lat("N455698735", "HDDMMmmmmm")
parse_lat("40.123째")
parse_lat("40.123N74.123W")
parse_lat("N45 04.25764")
# bad values -> NaN
parse_lat("191.89")
# many inputs
x <- c("40.123째", "40.123N74.123W", "191.89", 12, "N45 04.25764")
parse_lat(x)
```

longitudes

```{r}
parse_lon("45W54.2356")
parse_lon("-45.98739874")
parse_lon("N455698735", "HDDMMmmmmm")
parse_lon("40.123째")
parse_lon("40.123N74.123W")
parse_lon("N45 04.25764")
# bad values
parse_lon("181")
# many inputs
x <- c("45W54.2356", "181", 45, 45.234234, "-45.98739874")
parse_lon(x)
```

both lat and lon together

```{r}
lats <- c("40.123째", "40.123N74.123W", "191.89", 12, "N45 04.25764")
lons <- c("45W54.2356", "181", 45, 45.234234, "-45.98739874")
parse_lat_lon(lats, lons)
```
