# Generated by cpp11: do not edit by hand

pz_parse_lat <- function(x) {
  .Call("_parzer_pz_parse_lat", x)
}

pz_parse_lon <- function(x) {
  .Call("_parzer_pz_parse_lon", x)
}

pz_hemisphere <- function(lon, lat) {
  .Call("_parzer_pz_hemisphere", lon, lat)
}

split_decimal_degree <- function(x, fmt) {
  .Call("_parzer_split_decimal_degree", x, fmt)
}

pz_parse_parts_lat <- function(x) {
  .Call("_parzer_pz_parse_parts_lat", x)
}

pz_parse_parts_lon <- function(x) {
  .Call("_parzer_pz_parse_parts_lon", x)
}

pz_play <- function(x) {
  .Call("_parzer_pz_play", x)
}

pz_split_llstr <- function(x) {
  .Call("_parzer_pz_split_llstr", x)
}
