# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pz_parse_lat <- function(x) {
    .Call('_parzer_pz_parse_lat', PACKAGE = 'parzer', x)
}

pz_parse_lon <- function(x) {
    .Call('_parzer_pz_parse_lon', PACKAGE = 'parzer', x)
}

pz_hemisphere <- function(lon, lat) {
    .Call('_parzer_pz_hemisphere', PACKAGE = 'parzer', lon, lat)
}

split_decimal_degree <- function(x, fmt = "dms") {
    .Call('_parzer_split_decimal_degree', PACKAGE = 'parzer', x, fmt)
}

pz_parse_parts_lat <- function(x) {
    .Call('_parzer_pz_parse_parts_lat', PACKAGE = 'parzer', x)
}

pz_parse_parts_lon <- function(x) {
    .Call('_parzer_pz_parse_parts_lon', PACKAGE = 'parzer', x)
}

pz_split_llstr_string <- function(x) {
    .Call('_parzer_pz_split_llstr_string', PACKAGE = 'parzer', x)
}

pz_split_llstr <- function(x) {
    .Call('_parzer_pz_split_llstr', PACKAGE = 'parzer', x)
}

