# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convert_lat <- function(str) {
    .Call(`_parzer_convert_lat`, str)
}

convert_lon <- function(str) {
    .Call(`_parzer_convert_lon`, str)
}

pz_parse_lat <- function(x) {
    .Call(`_parzer_pz_parse_lat`, x)
}

pz_parse_lon <- function(x) {
    .Call(`_parzer_pz_parse_lon`, x)
}

pz_hemisphere <- function(lon, lat) {
    .Call(`_parzer_pz_hemisphere`, lon, lat)
}

split_decimal_degree <- function(x, fmt = "dms") {
    .Call(`_parzer_split_decimal_degree`, x, fmt)
}

pz_parse_parts_lat <- function(x) {
    .Call(`_parzer_pz_parse_parts_lat`, x)
}

pz_parse_parts_lon <- function(x) {
    .Call(`_parzer_pz_parse_parts_lon`, x)
}

pz_split_llstr_string <- function(x) {
    .Call(`_parzer_pz_split_llstr_string`, x)
}

pz_split_llstr <- function(x) {
    .Call(`_parzer_pz_split_llstr`, x)
}

