assert <- function(x, y) {
  if (!is.null(x)) {
    if (!inherits(x, y)) {
      stop(deparse(substitute(x)), " must be of class ",
           paste0(y, collapse = ", "), call. = FALSE)
    }
  }
}

lint_inputs <- function(lon = NULL, lat = NULL, format) {
  assert(lon, c("character", "numeric", "integer"))
  assert(lat, c("character", "numeric", "integer"))
  assert(format, "character")
}

# FIXME: stopgap for now until figure out how to replace these on on src side
# - single quotes
# - double quotes
# - degree symbols
# - masculine ordinal indicator
# - rare separators

scrub <- function(x) gsub("[^A-Za-z0-9\\.\\ ,'-]|d|g", "'", x)

stop_form <- function() stop("format handling not ready yet")

# Because of a std::regex's bug, all Rcpp functions hangs on Windows with MBCS
# locale (#31). As a workaround for this, wrap the functions with `withr::with_locale()`
# on building package.
if (identical(tolower(Sys.info()[["sysname"]]), "windows")
    || identical(Sys.getenv("PARZER_DEBUG_LOCALE_WRAPPER"), "true")) {

  # Get current environment
  parzer_ns <- environment()

  for (nm in ls(envir = parzer_ns)) {
    o <- get0(nm, mode = "function", inherits = FALSE, envir = parzer_ns)
    if (is.null(o)) {
      next
    }

    body(o) <- body(o)

    # e.g. function(x) x
    if (!identical(typeof(body(o)), "language")) {
      next
    }

    # Assume a function generated by Rcpp is
    # 1. the first element is `{`
    # 2. the second element is `.Call(...)`
    if (length(body(o)) != 2L ||
        !identical(body(o)[[1]], quote(`{`)) ||
        !identical(body(o)[[2]][[1]], quote(.Call))) {
      next
    }

    # `orig_body` will be replaced as the actual function later.
    wrapped_body <- quote(withr::with_locale(c(LC_COLLATE = "C"), orig_body))
    # Wrap the content of `body(o)` with withr::with_locale()
    wrapped_body[[3]] <- body(o)[[2]]
    body(o) <- wrapped_body

    assign(nm, o, envir = parzer_ns)
  }
}
