name: "New issue or new PR Greeter"
on: [pull_request, issues]
jobs:
  greeter:
    runs-on: ubuntu-latest
    steps:
      - name: "Greeter"
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '#Thanks! \nWe will look into it ASAP.'
          pr-message: 'Hey!, \nWelcome to this repo, thanks for your input, we will look into it ASAP.'
